app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from . import views
    
from graphene_django.views import GraphQLView

urlpatterns = [
    url(r'^test/', views.test),
    url(r'^giftcode/', views.giftcode, name='giftcode'),
    url(r'^api/v1/login', views.LoginView.as_view(), name='api_login'),
    url(r'^accounts/logout/$', auth_views.logout, {'next_page' : '/'}, name='logout'),
    url(r'^accounts/login/$', views.LoginView.as_view(), name='login'),
    url(r'^accounts/register/$', views.register, name='register'),
#    url(r'^accounts/', include('django.contrib.auth.urls')),

    url(r'^documents/upload/$', views.DocumentUploadView.as_view(), name='documents_upload'),
    url(r'^documents/list/$', views.DocumentListView.as_view(), name='documents_list'),
    url(r'^documents/(?P<pk>\d+)/$', views.DocumentDetailView.as_view(), name='documents_detail'),

   # url(r'^graphql/$', GraphQLView.as_view(graphiql=True)),
    url(r'^$', views.index, name='home'),
]

salaryman/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
#    url(r'^admin/', admin.site.urls),
    url(r'', include('app.urls', namespace='app')),
] 

app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    class Meta(AbstractUser.Meta):
        swappable = 'AUTH_USER_MODEL'
    REQUIRED_FIELDS = []
    is_admin = models.BooleanField(default=False)
    is_premium = models.BooleanField(default=False)
    gift_code = models.CharField(default='', max_length=32)

class Document(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='documents')   
    url = models.CharField(max_length=1024)
    name = models.CharField(max_length=256, blank=True)
    contents = models.TextField(blank=True)
    DOCX = 0
    PAGE = 1
    TYPES = (
        (0, 'Docx'),
        (1, 'Page'),
    ) 

    type = models.IntegerField(default=0, choices=TYPES) 
    status = models.CharField(default='Processing in 5 secs', max_length=16)
    status_message = models.CharField(default='', max_length=4096)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{}:{}:{}'.format(self.url, self.name, self.contents)

app/forms.py
from django import forms
from .models import (
    User,
    Document,
)

from django.contrib.auth.forms import UserCreationForm

class UserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username']

class DocumentUploadForm(forms.ModelForm):
    is_translate = forms.BooleanField(initial=False, required=False)
    class Meta:
        model = Document
        fields = ['url', 'type']
        
    def __init__(self, *args, **kwargs):
        super(DocumentUploadForm, self).__init__(*args, **kwargs)
        self.fields['type'].widget.attrs.update({
            'class': 'browser-default'
        })

app/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from urlparse import urlparse

from googletrans import Translator

from django.core.exceptions import (
    ObjectDoesNotExist,
    ValidationError,
)

from django.shortcuts import (
    render, 
    redirect, 
    HttpResponse
)

from django.http import (
 HttpResponseBadRequest,
 JsonResponse
)

from django.contrib.auth import (
    login,
    authenticate
)

from django.contrib.auth.views import LoginView as DjangoLoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required


from django.urls import reverse_lazy

from django.views.generic.edit import FormView
from django.views.generic import (
    ListView,
    DetailView,
)

from .tasks import  upload_document

from .forms import (
    UserCreationForm,
    DocumentUploadForm,
)

from .models import (
    User,
    Document,
)
from .schema import schema
# Create your views here.


def index(request):
    return render(request, 'index.html', context={})
    
def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('app:home')
    else:
        form = UserCreationForm()
        
    return render(request, 'registration/register.html', {'form': form})

@login_required
def giftcode(request):
    context = {}
    if request.method == 'POST':
        try:
            code = request.POST.get('code','')
            admin = User.objects.get(username='admin')
            if admin.gift_code.strip() == code.strip():
                request.user.is_premium = True
                request.user.save()
                context = {'message':'Correct! Hi Premium User! Go to Page Crawl Feature'}
            else:
                context = {'message':'Wrong! Login admin!'}
        except:
            context = {'message':'Unknown Error'}

    return render(request, 'giftcode.html', context)

class LoginView(DjangoLoginView):
    def post(self, request, *args, **kwargs):
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        if not (username and password):
            return HttpResponseBadRequest()
        #query = 'query {{ user(username:"{username}", password:"{password}") {{  id, email }} }}'.format(
        query = 'query {{ user(username:"{username}", password:"{password}") {{  id }} }}'.format(
            **{'username':username, 'password':password})

        result = schema.execute(query)
        
        errors = ['', str(result.errors)][result.errors != None]
        result = {'data': result.data, 'errors':errors}
        try:
            if 'does not exist' in result['errors']: 
                raise ObjectDoesNotExist()

            if not result['errors']: #user exists
                user = result['data']['user']
                if 'id' in user:
                    user = User.objects.get(pk=user['id'])
                    login(request, user)
                    return JsonResponse({'data':'Welcome! '+user.username, 'errors':None})
            return JsonResponse(result) #for debug

        except ObjectDoesNotExist:
            return JsonResponse({'data':None, 'errors':'Incorrect ID/PW'})
        except:
            return HttpResponseBadRequest()
            
      
class DocumentUploadView(LoginRequiredMixin, FormView):
    template_name = 'documents/upload.html'
    form_class = DocumentUploadForm 
    success_url = reverse_lazy('app:documents_list')

    def form_valid(self, form):
        type = form.cleaned_data['type']
        url = form.cleaned_data['url']
        is_translate = form.cleaned_data['is_translate']

        user = self.request.user

        if user.is_admin:
            form._errors[''] = 'Admin is not availiable'
            return self.form_invalid(form)

        result = urlparse(url)
        scheme = result.scheme
        if not scheme:
            form._errors[''] = 'Required URL scheme'
            return self.form_invalid(form)
        if scheme == 'file':
            form._errors[''] = "Nice Try, Don't SSRF ! "
            return self.form_invalid(form)
            
        if type == Document.PAGE and not user.is_premium:
            form._errors[''] = 'Page is only for PREMIUM'
            return self.form_invalid(form)

                
        upload_document.delay(user, url, type, is_translate)
        
        return super(DocumentUploadView, self).form_valid(form)

    def form_invalid(self, form):
        type = form.cleaned_data['type']
        return super(DocumentUploadView, self).form_invalid(form)


class DocumentListView(LoginRequiredMixin, ListView):
    template_name = 'documents/list.html'
    context_object_name = 'documents' 

    def get_queryset(self): 
        if self.request.user.is_authenticated:
            return self.request.user.documents.all()
        return None


class DocumentDetailView(LoginRequiredMixin, DetailView):
    template_name = 'documents/detail.html'
    model = Document
    context_object_name = 'document' 
    def get_context_data(self, **kwargs):
        try:
            document = Document.objects.get(user=self.request.user,pk=self.kwargs['pk'])
        except Exception as e:
            document = None
        return {'document':document}
            
def test(request):
    return render(request, 'add.html')

app/templates/base.html
{% load static %}
{% include 'material/includes/material_css.html' %}
{% include 'material/includes/material_js.html' %}

<head>

       
</head>
<body>
    <div class="page-header">
    <nav>
        <div class="nav-wrapper">
        <a href="/" class="brand-logo center">Doc Reader</a>
                
        <ul id="nav-mobile" class="left hide-on-med-and-down">
            <li class="left waves-effect"><a href="{% url 'app:documents_upload'%}" >Upload</a></li>
            <li class="left waves-effect"><a href="{% url 'app:documents_list'%}" >List</a></li>
        </ul>

        <ul id="nav-mobile" class="right hide-on-med-and-down">
            {% if not request.user.is_premium %}
            <li class="left waves-effect"><a href="{% url 'app:giftcode' %}">Secret Premium GIFT CODE</a></li>
            {% endif %}
            {% if not request.user.is_authenticated %}
            <li class="left waves-effect"><a href="{% url 'app:login' %}">Login</a></li>
            <li class="left waves-effect"><a href="{% url 'app:register' %}">Register</a></li>
            {% else %}
            <li class="left waves-effect">Hello {{request.user.username}} !</li>
            <li class="left waves-effect"><a href="{% url 'app:logout' %}">Logout</a></li>
            {% endif %}
        </ul>
        </div>
            
        </nav>
            
    </div>
    
    <div class="content container">
        
        <div class="row">
            
            <div class="col-md-8">
                <h3 class="blue-text">{% block title %}
                    {% endblock %}
                </h3>
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div>
</body>

app/templates/documents/detail.html
{% extends 'base.html' %}
{% block title %}
Document Detail
{% endblock %}

{% block content %}

<div style="overflow-x:scroll">
<table class="highlight">
        <thead>
                <tr>
                        <th>Type </th>
                        <td>
                        {% if document.type == 0 %}
                        Docx
                        {% else %}
                        Page
                        {% endif %}
                        </td>
                </tr>
                <tr>
                        <th>Name</th>
                                        <td>{{document.name}}</td>
                </tr>
                <tr>
                        <th>URL</th>
                        <td>{{document.url}}</td>
                </tr>
                <tr>
                        <th>Date</th>
                        <td>{{document.created_at}}</td>
                </tr>
                <tr>
                        <th>Contents</th>
                        
                        <td>{{document.contents}}</td>
                </tr>
                <tr>
                        <th>Status</th>
                        {% if 'Process' in document.status %}
                        <td class="orange-text">
                        {% elif 'Fail' in document.status %}
                        <td class="red-text">
                        {% else %}
                        <td class="green-text">
                        {% endif %}
                        {{document.status}}
                        </td>
                </tr>
                <tr>
                        <th>Status Message</th>
                        {% if 'Process' in document.status %}
                        <td class="orange-text">
                        {% elif 'Fail' in document.status %}
                        <td class="red-text">
                        {% else %}
                        <td class="green-text">
                        {% endif %}
                        {{document.status_message}}
                        </td>
                </tr>
        </thead>
</table>
</div>
<script>
s = document.getElementById("asdf").innerHTML;
document.getElementById("asdf").innerHTML = s.replace(/[<>]/,"");
</script>
{% endblock %}

app/templates/documents/list.html
{% extends 'base.html' %}
{% block title %}
Document List
{% endblock %}

{% block content %}

<table class="highlight">
        <thead>
                <tr>
                <th>Type </th>
                <th>Name</th>
                <th>URL</th>
                <th>Date</th>
                <th>Contents</th>
                <th>Status</th>
                </tr>
        </thead>

        <tbody>
                {% for document in documents %}
                <tr onclick="window.location='{% url 'app:documents_detail' document.id %}'">
                <td>
                {% if document.type == 0 %}
                Docx
                {% else %}
                Page
                {% endif %}
                </td>
                <td>{{document.name}}</td>
                <td>{{document.url}}</td>
                <td>{{document.created_at}}</td>
                <td>{{document.contents|truncatechars:30}}</td>
                {% if 'Process' in document.status %}
                <td class="orange-text">
                {% elif 'Fail' in document.status %}
                <td class="red-text">
                {% else %}
                <td class="green-text">
                {% endif %}
                {{document.status}}</td>
                </tr>
                {% endfor %}
        </tbody>
</table>


{% endblock %}

app/templates/documents/upload.html
{% extends 'base.html' %}
{% load material_form %}
<script>
 document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('select');
    var instances = M.FormSelect.init(elems, options);
  });
</script>
{% block title %}
Document Upload
{% endblock %}

{% block content %}

<form method="post" action="{% url 'app:documents_upload' %}" id="form_login">
{% csrf_token %}
{% form form=form %} {% endform %}
    <div class="error">
    {{ form.errors }}
    </div>
    <button name="_submit" type="submit" class="btn" >Upload</button>
</form>

{% endblock %}

app/templates/giftcode.html
{% extends 'base.html' %}
{% block title %}
Premium GIFT CODE
{% endblock %}

{% block content %}
{% if request.user.is_admin %}
    {{request.user.gift_code}}
{% else %}
</p>
<p>
Only admin can read, please login admin, get your Gift code, and become PREMIUM User!
</p>
{% endif %}
<p>
If you have PREMIUM GIFT Code, Submit!
</p>
<form method="post" action="." id="form_giftcode">
{% csrf_token %}
    <div class="input-field  required">
        <input id="id_code" type="text" name="code" value="" />
        <label for="id_code" class="active">Code</label>
        {{ form.as_p }}
    </div>
    <div class="error">

        {{ message }}
    </div>
    <button type="submit" name="_submit" class="btn">Submit</button>
</form>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}
{% block content %}
/run.sh
{% endblock %}